version: '2'
services:
  youcham-admin:
    image: youcham/admin
    ports:
      - "8080:8080"
    environment:
      - spring.profiles.active=dev
  youcham-api:
    image: youcham/api
    ports:
      - "8081:8081"
    environment:
      - spring.profiles.active=dev