spring:
    datasource:
        db1:
            type: com.alibaba.druid.pool.DruidDataSource
            driverClassName: oracle.jdbc.driver.OracleDriver
            druid:
                first:  #数据源1
                    url: jdbc:oracle:thin:@//47.96.116.15:1521/ORCL
                    username: wzgxfb
                    password: wzgxfb_2219##
                second:  #数据源2
                    url: jdbc:oracle:thin:@//47.96.116.15:1521/ORCL
                    username: wzgxfb
                    password: wzgxfb_2219##
                mega:  #数据源2
                    url: jdbc:oracle:thin:@//47.96.116.15:1521/ORCL
                    username: wzgxfb
                    password: wzgxfb_2219##
                initial-size: 10
                max-active: 100
                min-idle: 10
                max-wait: 60000
                pool-prepared-statements: true
                max-pool-prepared-statement-per-connection-size: 20
                time-between-eviction-runs-millis: 60000
                min-evictable-idle-time-millis: 300000
                #validation-query: SELECT 1 FROM DUAL
                test-while-idle: true
                test-on-borrow: false
                test-on-return: false
                stat-view-servlet:
                    enabled: true
                    url-pattern: /druid/*
                    #login-username: admin
                    #login-password: admin
                filter:
                    stat:
                        log-slow-sql: true
                        slow-sql-millis: 1000
                        merge-sql: false
                    wall:
                        config:
                            multi-statement-allow: true
        db2:
            type: com.alibaba.druid.pool.DruidDataSource
            driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
            druid:
                first:  #数据源1
                    url: jdbc:sqlserver://localhost:1433;DatabaseName=zsyz
                    username: sa
                    password: 123456]
                two:  #数据源2
                    url: jdbc:sqlserver://192.168.0.111;DatabaseName=yjjc
                    username: sa
                    password: 123456
                initial-size: 10
                max-active: 100
                min-idle: 10
                max-wait: 60000
                pool-prepared-statements: true
                max-pool-prepared-statement-per-connection-size: 20
                time-between-eviction-runs-millis: 60000
                min-evictable-idle-time-millis: 300000
                #validation-query: SELECT 1 FROM DUAL
                test-while-idle: true
                test-on-borrow: false
                test-on-return: false
                stat-view-servlet:
                    enabled: true
                    url-pattern: /druid/*
                    #login-username: admin
                    #login-password: admin
                filter:
                    stat:
                        log-slow-sql: true
                        slow-sql-millis: 1000
                        merge-sql: false
                    wall:
                        config:
                            multi-statement-allow: true

     
    