# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30 
        disableUploadTimeout: false 
    port: 8081
    servlet:
        context-path: /

# mysql
spring:
    # 环境 dev|test|prod
    jmx:
        default-domain: JJST-CHK
    profiles:
        active: test
    servlet:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
            enabled: true
    redis:
        database: 0
        host: localhost
        port: 6379
        password:      # 密码（默认为空）
        timeout: 6000ms  # 连接超时时长（毫秒）
        jedis:
            pool:
                max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
                max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
                max-idle: 10      # 连接池中的最大空闲连接
                min-idle: 5       # 连接池中的最小空闲连接
    freemarker:
      suffix: .html
      request-context-attribute: request
    taskJob:
      swzjInitProjectCurrYearJz: 0 0 0 1 1 ? # 重置项目当年累计进资  #每年 一月一号 0:0:0
      swzjChangeProjectType: 0 0 0 1 1 ? # 每年改变开工纳入统计项目类型为非本年纳入统计  #每年 一月一号 0:0:0
      swzjInitProjectCurrMonthJz: 0 0 0 1 * ? # 重置项目当月累计进资  #每年 每月一号 0:0:0
      swzjAutoDelayProject: 0 0 0 1 * ? # 每月自动把超时审核项目过期  #每年 每月一号 0:0:0   0 0 0 1 * ?
      swzjAutoAuditJz: 0 0 0 1 * ? # 每月自动审核进资  #每年 每月一号 0:0:0   0 0 0 1 * ?
      swzjAutoDownload: 0 0 0 * * ? # 秒,分,时,日,月,星期   每月自动下载身外资金报表
youcham:
    redis:
        open: false  # 是否开启redis缓存  true开启   false关闭
    shiro:
        redis: false # true表示shiro session存到redis里，需要开启redis，才会生效【分布式场景】
    scheduling:
        enabled: true # 是否开启定时任务

#mybatis
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: io.youcham.modules.*.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 3
    #字段策略 0:"忽略判断",1:"非 NULL 判断",2:"非空判断"
    field-strategy: 1
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    # Sequence序列接口实现类配置
    #key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
    #逻辑删除配置
    logic-delete-value: -1
    logic-not-delete-value: 0
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.xxx
    #自定义SQL注入器
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    #配置JdbcTypeForNull, oracle数据库必须配置
    jdbc-type-for-null: 'null' 
    
#cas
cas:
  client-name: inspect
  server:
    url: http://127.0.0.1:8443/cas
  project:
    url: http://127.0.0.1:${server.port}
  user-center: 
    url: http://172.16.0.33:8888/user-center/

#FTP
ftp:
  host: 10.97.10.79
  port: 21
  username: stfuser
  password: stsh@2019
  filepath: /home/data

activiti: # activiti 默认配置
  database-schema-update: true
  database_schema: ACTIVITI
  check-process-definitions: true
  process-definition-location-prefix: classpath:/processes/
  #process-definition-location-suffixes:**.bpmn - **.bpmn20.xml

logging:
  level: debug
  level.io.youcham: debug
  path: logs/
  file: admin.log


